name: "delete-releases-workflows"
author: "ophub"
description: "Delete older releases and workflow runs"
inputs:
  repo:
    description: "Repo name in the form of <owner>/<repo>"
    required: false
    default: "${{ github.repository }}"
  delete_releases:
    description: "Whether to delete releases records"
    required: true
    default: ""
  delete_tags:
    description: "Whether to delete associated tags"
    required: false
    default: "true"
  prerelease_option:
    description: "Whether to differentiate pre-release"
    required: false
    default: "all"
  releases_keep_latest:
    description: "How many latest releases to keep"
    required: false
    default: "90"
  releases_keep_keyword:
    description: "Keyword of the keep releases"
    required: false
    default: ""
  max_releases_fetch:
    description: "Maximum number of releases to fetch in total"
    required: false
    default: "200"
  delete_workflows:
    description: "Whether to delete workflows records"
    required: true
    default: ""
  workflows_keep_latest:
    description: "How many latest workflow runs to keep"
    required: false
    default: "90"
  workflows_keep_keyword:
    description: "Keywords for keep workflows"
    required: false
    default: ""
  out_log:
    description: "Output a list log for each step"
    required: false
    default: "false"
  gh_token:
    description: "Set the token"
    required: true
    default: ""
  max_workflows_fetch:
    description: "Maximum number of workflow runs to fetch in total"
    required: false
    default: "200"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Use GITHUB_WORKSPACE to get the current workspace directory
        GITHUB_ACTION_PATH="${{ github.action_path }}"
        cd "$GITHUB_ACTION_PATH"

        # 所有应用参数
        gh_token="${{ inputs.gh_token }}"
        delete_releases="${{ inputs.delete_releases }}"
        delete_tags="${{ inputs.delete_tags }}"
        prerelease_option="${{ inputs.prerelease_option }}"
        releases_keep_latest="${{ inputs.releases_keep_latest }}"
        releases_keep_keyword="${{ inputs.releases_keep_keyword }}"
        max_releases_fetch="${{ inputs.max_releases_fetch }}"
        delete_workflows="${{ inputs.delete_workflows }}"
        workflows_keep_latest="${{ inputs.workflows_keep_latest }}"
        workflows_keep_keyword="${{ inputs.workflows_keep_keyword }}"
        max_workflows_fetch="${{ inputs.max_workflows_fetch }}"
        out_log="${{ inputs.out_log }}"
        repo="${{ inputs.repo }}"

        # 错误提示颜色
        ERROR="[\033[91m ERROR \033[0m]"
        error_msg() {
            echo -e "${ERROR} ${1}"
            exit 1
        }

        # 验证必需参数,如果参数为空则会停止整个脚本运行
        [[ -z "${gh_token}" ]] && error_msg "必须设置 [ gh_token ] 参数，且参数为正确密钥"
        [[ -z "${delete_releases}" ]] && error_msg "必须设置 [ delete_releases ] 参数，且参数为 'true' 或 'false'"
        [[ -z "${delete_workflows}" ]] && error_msg "必须设置 [ delete_workflows ] 参数，且参数为 'true' 或 'false'"
        [[ ! -f "del.sh" ]] && error_msg "未知原因，找不到 [ del.sh ] 执行文件"

        delete_releases="${delete_releases//[[:space:]]/}"
        delete_tags="${delete_tags//[[:space:]]/}"
        prerelease_option="${prerelease_option//[[:space:]]/}"
        releases_keep_latest="${releases_keep_latest//[[:space:]]/}"
        releases_keep_keyword="${releases_keep_keyword//[[:space:]]/}"
        max_releases_fetch="${max_releases_fetch//[[:space:]]/}"
        delete_workflows="${delete_workflows//[[:space:]]/}"
        workflows_keep_latest="${workflows_keep_latest//[[:space:]]/}"
        workflows_keep_keyword="${workflows_keep_keyword//[[:space:]]/}"
        max_workflows_fetch="${max_workflows_fetch//[[:space:]]/}"
        out_log="${out_log//[[:space:]]/}"
        repo="${repo//[[:space:]]/}"

        # 构建命令行参数
        make_command=""
        [[ -n "${repo}" ]] && make_command="${make_command} -r ${repo}"
        [[ -n "${delete_releases}" ]] && make_command="${make_command} -a ${delete_releases}"
        [[ -n "${delete_tags}" ]] && make_command="${make_command} -t ${delete_tags}"
        [[ -n "${prerelease_option}" ]] && make_command="${make_command} -p ${prerelease_option}"
        [[ -n "${releases_keep_latest}" ]] && make_command="${make_command} -l ${releases_keep_latest}"
        [[ -n "${releases_keep_keyword}" ]] && make_command="${make_command} -w ${releases_keep_keyword}"
        [[ -n "${max_releases_fetch}" ]] && make_command="${make_command} -c ${max_releases_fetch}"
        [[ -n "${delete_workflows}" ]] && make_command="${make_command} -s ${delete_workflows}"
        [[ -n "${workflows_keep_latest}" ]] && make_command="${make_command} -d ${workflows_keep_latest}"
        [[ -n "${workflows_keep_keyword}" ]] && make_command="${make_command} -k ${workflows_keep_keyword}"
        [[ -n "${max_workflows_fetch}" ]] && make_command="${make_command} -h ${max_workflows_fetch}"
        [[ -n "${gh_token}" ]] && make_command="${make_command} -g ${gh_token}"
        [[ -n "${out_log}" ]] && make_command="${make_command} -o ${out_log}"

        # 执行脚本
        chmod +x del.sh
        ./del.sh ${make_command}

branding:
  icon: "terminal"
  color: "gray-dark"
