name: "delete-releases-workflows"
author: "ophub"
description: "Delete older releases and workflow runs"
inputs:
  repo:
    description: "Repo name in the form of <owner>/<repo>"
    required: false
    default: "${{ github.repository }}"
  delete_releases:
    description: "Whether to delete releases records"
    required: true
    default: ""
  delete_tags:
    description: "Whether to delete associated tags"
    required: false
    default: "true"
  prerelease_option:
    description: "Whether to differentiate pre-release"
    required: false
    default: "all"
  releases_keep_latest:
    description: "How many latest releases to keep"
    required: false
    default: "90"
  releases_keep_keyword:
    description: "Keyword of the keep releases"
    required: false
    default: ""
  max_releases_fetch:
    description: "Maximum number of releases to fetch in total"
    required: false
    default: "200"
  delete_workflows:
    description: "Whether to delete workflows records"
    required: true
    default: ""
  workflows_keep_latest:
    description: "How many latest workflow runs to keep"
    required: false
    default: "90"
  workflows_keep_keyword:
    description: "Keywords for keep workflows"
    required: false
    default: ""
  max_workflows_fetch:
    description: "Maximum number of workflow runs to fetch in total"
    required: false
    default: "200"
  out_log:
    description: "Output a list log for each step"
    required: false
    default: "false"
  gh_token:
    description: "Set the token"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        GITHUB_ACTION_PATH="${{ github.action_path }}"
        cd "$GITHUB_ACTION_PATH"
        chmod +x del.sh
        ./del.sh
      env:
        repo: ${{ inputs.repo }}
        delete_releases: ${{ inputs.delete_releases }}
        delete_tags: ${{ inputs.delete_tags }}
        prerelease_option: ${{ inputs.prerelease_option }}
        releases_keep_latest: ${{ inputs.releases_keep_latest }}
        releases_keep_keyword: ${{ inputs.releases_keep_keyword }}
        max_releases_fetch: ${{ inputs.max_releases_fetch }}
        delete_workflows: ${{ inputs.delete_workflows }}
        workflows_keep_latest: ${{ inputs.workflows_keep_latest }}
        workflows_keep_keyword: ${{ inputs.workflows_keep_keyword }}
        max_workflows_fetch: ${{ inputs.max_workflows_fetch }}
        gh_token: ${{ inputs.gh_token }}
        out_log: ${{ inputs.out_log }}

branding:
  icon: "terminal"
  color: "gray-dark"
